### ISSUE TITLE
'do' keyword in Ruby

### ISSUE THREAD

**Issue by PatrickLerner** [biletskyy/flatwhite-syntax#1]
See here where it highlights the space after the do:

![screen shot 2016-08-12 at 18 09 34](https://cloud.githubusercontent.com/assets/1738261/17628935/f9ad9522-60b7-11e6-8175-f1b9322cb748.png)

``` ruby
json.value object.value
json.to_param object.to_param
json.words object.words_for_user(current_user) do |word|
  json.extract! word, :value, :to_param, :language_id, :id
  json.language word.language.name
  json.notes word.notes.pluck(:value)
end
```

Btw. Love the style and keeping an eye on it, even if lacks too much language support (coffeescript, slim) for me to use it full time yet.

**Comment by biletskyy** [comment]
Thank you for your feedback, I'm glad that you like this theme. I will try to add more language support next week. 

Unfortunatelly, I don't know how to remove coloring of the space after `do`. It puts space inside colored `<span>`. 

`<span class="keyword control start-block ruby">do </span>` 

Maybe there is some hack to remove it, but i can't think of any right now.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag. So I'm gonna close as it seems fully resolved as far as I can see.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag. So I'm gonna close as it seems fully resolved as far as I can see.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag. So I'm gonna close as it seems fully resolved as far as I can see.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag.

**Comment by PatrickLerner** [comment]
I'm not really sure why, but it seems with the newest version of Atom the build-in ruby syntax is no longer producing this erroneous output where the space is inside of the tag.
