### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by Dekker1** [biletskyy/flatwhite-syntax#11]
I've been using this theme for a bit more than a week now and I'm loving it. One of the languages I use often though is missing support though: LaTeX (package: `language-latex`).

Expected support would be like MarkDown. Both languages aim to typeset documents and have similar priorities.

Let me know if I can provide any more details you might be able to use.

**Comment by biletskyy** [comment]
I'm really glad to hear that you like this theme :) I'll try to add LaTeX support asap. 
It will help if you can give me a link to good sample LaTeX document.

**Comment by Dekker1** [comment]
That's great news!

[This website](http://www.tug.org/pracjourn/2006-2/eglen/) offers a short example of a scientific paper in LaTeX. It should provide a good example. The actual LaTeX file is located [here](http://www.damtp.cam.ac.uk/user/eglen/texintro/intro.tex).

**Comment by biletskyy** [comment]
I finally added LaTeX support. It was harder then i thought it would be. But I think it looks ok. Please, test it and tell me if something needs to be updated from your real experience.
