### ISSUE TITLE
Elm support

### ISSUE THREAD

**Issue by sunsunych** [biletskyy/flatwhite-syntax#14]
Hi Dmitriy @biletskyy 
Thank you for easy to read and light theme. Started using it recently and already love it. It would be great if you can add Elm language support. Here is [Examples](http://elm-lang.org/examples) and [Syntax Doc](http://elm-lang.org/docs/syntax). 

Thank you once again!

**Comment by biletskyy** [comment]
Hi @sunsunych. It's nice to hear that you like this theme, thank you :)
I tried to add Elm support in past, but i didn't like my results so i dropped this task.

But I'll give it another try in a few days.

**Comment by MaxBittker** [comment]
@biletskyy sorry for hijacking this issue, just wanted to pop in and say I really enjoy the unique theme.  cheers

**Comment by biletskyy** [comment]
Hi @sunsunych, 
I added some Elm support. But I don't like how elm-language grammar works. So I'll try to improve highlighting later.
Please, tell me if you know what it's lacking or how it can be improved.
