### ISSUE TITLE
Highlight symbols in clojure 

### ISSUE THREAD

**Issue by torbjornvatn** [biletskyy/flatwhite-syntax#19]
I find this a bit hard to read as there are no color difference between the function and the arguments:
<img width="582" alt="screen shot 2016-10-25 at 22 22 45" src="https://cloud.githubusercontent.com/assets/4453/19702827/9b11e520-9b01-11e6-82bc-390a589ca144.png">

Could it be possible to add a highlight to `.symbol.clojure` as well?

Maybe something like this (here I'm using `.teal`)?
<img width="581" alt="screen shot 2016-10-25 at 22 25 42" src="https://cloud.githubusercontent.com/assets/4453/19702922/018b4a8a-9b02-11e6-8568-a8d7f64228f4.png">

**Comment by torbjornvatn** [comment]
Any thought in this?

**Comment by MaxBittker** [comment]
aren't functions also symbols? (this is the lisp 1\2 thing isn't it)

**Comment by torbjornvatn** [comment]
I'm not sure, but when I added the .teal highlight to .symbol.clojure I got the effect in the screenshot
