### ISSUE TITLE
Override background color

### ISSUE THREAD

**Issue by davelandry** [biletskyy/flatwhite-syntax#22]
Love the syntax highlighting. Would it be possible to get a config option to override the background color?

**Comment by MaxBittker** [comment]
do you want to make it lighter? just curious

**Comment by davelandry** [comment]
Yeah, I'd personally prefer something closer to white, but I get what you're going for with the low contrast ratio.

I generally use a dark theme, so I'd also love to try something like this out with a dark background as well (maybe a "flatblack-syntax"?). I just LOVE the syntax highlighting you've implemented.

**Comment by biletskyy** [comment]
@davelandry Thank you for your interest in this theme :)
Unfortunately, I'm not planning to add that background config option. I strongly believe that less config is better.

But you can easily change it yourself. 
There is custom stylesheet in Atom, you can read more about it here http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks

you just need to uncomment single line in it

`atom-text-editor {`
`  // color: white;`
`  // background-color: hsl(180, 24%, 90%);`
`}`

In this theme background color is `hsl(35, 36%, 95%)`. By increasing last value you make it lighter. 100% will be white.

Hope it helps :)

**Comment by biletskyy** [comment]
@davelandry Considering dark version, I thought about it, but i don't see a way to convert it into dark colors. But there are two people who tried to convert it, hope they will succeed 
https://github.com/PFCM/longblack-syntax
https://github.com/Willamin/flatdark-syntax
