### ISSUE TITLE
Deprecated selectors starting from Atom v1.13.0

### ISSUE THREAD

**Issue by vldmkrsh** [biletskyy/flatwhite-syntax#25]
> Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`.

Please, update theme for Atom v1.13.0.

**Comment by biletskyy** [comment]
fixed. sorry for long delay.

**Comment by vldmkrsh** [comment]
Thank you!
