### ISSUE TITLE
Deprecated selector in "flatwhite-syntax/index.less"

### ISSUE THREAD

**Issue by remifan** [biletskyy/flatwhite-syntax#26]
Atom version: 1.14.2

in "flatwhite-syntax/index.less"
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
atom-text-editor, :host => atom-text-editor,atom-text-editor
atom-text-editor .line.cursor-line, :host .line.cursor-line => atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line
atom-text-editor .invisible, :host .invisible => atom-text-editor .invisible,atom-text-editor .invisible
atom-text-editor .cursor, :host .cursor => atom-text-editor .cursor,atom-text-editor .cursor
atom-text-editor .selection .region, :host .selection .region => atom-text-editor .selection .region,atom-text-editor .selection .region
atom-text-editor .bracket-matcher .region, :host .bracket-matcher .region => atom-text-editor .bracket-matcher .region,atom-text-editor .bracket-matcher .region
atom-text-editor .invisible-character, :host .invisible-character => atom-text-editor .invisible-character,atom-text-editor .invisible-character
atom-text-editor .indent-guide, :host .indent-guide => atom-text-editor .indent-guide,atom-text-editor .indent-guide
atom-text-editor .wrap-guide, :host .wrap-guide => atom-text-editor .wrap-guide,atom-text-editor .wrap-guide
atom-text-editor .find-result .region.region.region, :host .find-result .region.region.region, atom-text-editor .current-result .region.region.region, :host .current-result .region.region.region => atom-text-editor .find-result .region.region.region,atom-text-editor .find-result .region.region.region, atom-text-editor .current-result .region.region.region,atom-text-editor .current-result .region.region.region
atom-text-editor .find-result .region.region.region, :host .find-result .region.region.region => atom-text-editor .find-result .region.region.region,atom-text-editor .find-result .region.region.region
atom-text-editor .current-result .region.region.region, :host .current-result .region.region.region => atom-text-editor .current-result .region.region.region,atom-text-editor .current-result .region.region.region
atom-text-editor .gutter .line-number, :host .gutter .line-number => atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number
atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line => atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line
atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection => atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection
atom-text-editor .gutter .line-number .icon-right, :host .gutter .line-number .icon-right => atom-text-editor .gutter .line-number .icon-right,atom-text-editor .gutter .line-number .icon-right
atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before, :host .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before => atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before
atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after, :host .gutter:not(.git-diff-icon) .line-number.git-line-removed::after => atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after
atom-text-editor .gutter .line-number.folded, :host .gutter .line-number.folded, atom-text-editor .gutter .line-number:after, :host .gutter .line-number:after, atom-text-editor .fold-marker:after, :host .fold-marker:after => atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded, atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after, atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after
.base => .syntax--base
.comment => .syntax--comment
.green => .syntax--green
.blue => .syntax--blue
.reset => .syntax--reset
.reset_all .keyword.control, .reset_all .string.quoted, .reset_all .string.regexp, .reset_all .constant.numeric, .reset_all .constant.keyword, .reset_all .constant.symbol, .reset_all .constant.language, .reset_all .entity.name.tag, .reset_all .meta.embedded => .reset_all .syntax--keyword.syntax--control, .reset_all .syntax--string.syntax--quoted, .reset_all .syntax--string.syntax--regexp, .reset_all .syntax--constant.syntax--numeric, .reset_all .syntax--constant.syntax--keyword, .reset_all .syntax--constant.syntax--symbol, .reset_all .syntax--constant.syntax--language, .reset_all .syntax--entity.syntax--name.syntax--tag, .reset_all .syntax--meta.syntax--embedded
.reset_all .meta.embedded .punctuation.embedded => .reset_all .syntax--meta.syntax--embedded .syntax--punctuation.syntax--embedded
.reset_all .meta.embedded .string.quoted .punctuation.definition => .reset_all .syntax--meta.syntax--embedded .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.keyword.control => .syntax--keyword.syntax--control
.constant.keyword, .constant.symbol => .syntax--constant.syntax--keyword, .syntax--constant.syntax--symbol
.constant.numeric, .constant.language => .syntax--constant.syntax--numeric, .syntax--constant.syntax--language
.string.quoted, .string.regexp => .syntax--string.syntax--quoted, .syntax--string.syntax--regexp
.string.quoted .keyword.control, .string.regexp .keyword.control, .string.quoted .string.quoted, .string.regexp .string.quoted, .string.quoted .string.regexp, .string.regexp .string.regexp, .string.quoted .constant.numeric, .string.regexp .constant.numeric, .string.quoted .constant.keyword, .string.regexp .constant.keyword, .string.quoted .constant.symbol, .string.regexp .constant.symbol, .string.quoted .constant.language, .string.regexp .constant.language, .string.quoted .entity.name.tag, .string.regexp .entity.name.tag, .string.quoted .meta.embedded, .string.regexp .meta.embedded => .syntax--string.syntax--quoted .syntax--keyword.syntax--control, .syntax--string.syntax--regexp .syntax--keyword.syntax--control, .syntax--string.syntax--quoted .syntax--string.syntax--quoted, .syntax--string.syntax--regexp .syntax--string.syntax--quoted, .syntax--string.syntax--quoted .syntax--string.syntax--regexp, .syntax--string.syntax--regexp .syntax--string.syntax--regexp, .syntax--string.syntax--quoted .syntax--constant.syntax--numeric, .syntax--string.syntax--regexp .syntax--constant.syntax--numeric, .syntax--string.syntax--quoted .syntax--constant.syntax--keyword, .syntax--string.syntax--regexp .syntax--constant.syntax--keyword, .syntax--string.syntax--quoted .syntax--constant.syntax--symbol, .syntax--string.syntax--regexp .syntax--constant.syntax--symbol, .syntax--string.syntax--quoted .syntax--constant.syntax--language, .syntax--string.syntax--regexp .syntax--constant.syntax--language, .syntax--string.syntax--quoted .syntax--entity.syntax--name.syntax--tag, .syntax--string.syntax--regexp .syntax--entity.syntax--name.syntax--tag, .syntax--string.syntax--quoted .syntax--meta.syntax--embedded, .syntax--string.syntax--regexp .syntax--meta.syntax--embedded
.string.quoted .meta.embedded .punctuation.embedded, .string.regexp .meta.embedded .punctuation.embedded => .syntax--string.syntax--quoted .syntax--meta.syntax--embedded .syntax--punctuation.syntax--embedded, .syntax--string.syntax--regexp .syntax--meta.syntax--embedded .syntax--punctuation.syntax--embedded
.string.quoted .meta.embedded .string.quoted .punctuation.definition, .string.regexp .meta.embedded .string.quoted .punctuation.definition => .syntax--string.syntax--quoted .syntax--meta.syntax--embedded .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition, .syntax--string.syntax--regexp .syntax--meta.syntax--embedded .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.string.quoted .punctuation.definition, .string.regexp .punctuation.definition => .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition, .syntax--string.syntax--regexp .syntax--punctuation.syntax--definition
.comment => .syntax--comment
.meta.embedded:not(.php) .punctuation.embedded => .syntax--meta.syntax--embedded:not(.php) .syntax--punctuation.syntax--embedded
.bold => .syntax--bold
.italic => .syntax--italic
.invalid.deprecated => .syntax--invalid.syntax--deprecated
.invalid.illegal => .syntax--invalid.syntax--illegal
.embedded-simple-mix .keyword.control, .embedded-simple-mix .string.quoted, .embedded-simple-mix .string.regexp, .embedded-simple-mix .constant.numeric, .embedded-simple-mix .constant.keyword, .embedded-simple-mix .constant.symbol, .embedded-simple-mix .constant.language, .embedded-simple-mix .entity.name.tag, .embedded-simple-mix .meta.embedded => .embedded-simple-mix .syntax--keyword.syntax--control, .embedded-simple-mix .syntax--string.syntax--quoted, .embedded-simple-mix .syntax--string.syntax--regexp, .embedded-simple-mix .syntax--constant.syntax--numeric, .embedded-simple-mix .syntax--constant.syntax--keyword, .embedded-simple-mix .syntax--constant.syntax--symbol, .embedded-simple-mix .syntax--constant.syntax--language, .embedded-simple-mix .syntax--entity.syntax--name.syntax--tag, .embedded-simple-mix .syntax--meta.syntax--embedded
.embedded-simple-mix .meta.embedded .punctuation.embedded => .embedded-simple-mix .syntax--meta.syntax--embedded .syntax--punctuation.syntax--embedded
.embedded-simple-mix .meta.embedded .string.quoted .punctuation.definition => .embedded-simple-mix .syntax--meta.syntax--embedded .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.embedded-simple-mix .punctuation.embedded => .embedded-simple-mix .syntax--punctuation.syntax--embedded
.embedded-full-mix .punctuation.embedded => .embedded-full-mix .syntax--punctuation.syntax--embedded
.source.c .storage.type => .syntax--source.syntax--c .syntax--storage.syntax--type
.source.clojure .storage.control => .syntax--source.syntax--clojure .syntax--storage.syntax--control
.ink.result.inline .ink.leaf .text => .syntax--ink.syntax--result.syntax--inline .syntax--ink.syntax--leaf .syntax--text
.source.coffee .storage.type.class, .source.coffee .storage.type.function, .source.coffee .meta.inline.function => .syntax--source.syntax--coffee .syntax--storage.syntax--type.syntax--class, .syntax--source.syntax--coffee .syntax--storage.syntax--type.syntax--function, .syntax--source.syntax--coffee .syntax--meta.syntax--inline.syntax--function
.source.coffee .storage.type.class .function, .source.coffee .storage.type.function .function, .source.coffee .meta.inline.function .function => .syntax--source.syntax--coffee .syntax--storage.syntax--type.syntax--class .syntax--function, .syntax--source.syntax--coffee .syntax--storage.syntax--type.syntax--function .syntax--function, .syntax--source.syntax--coffee .syntax--meta.syntax--inline.syntax--function .syntax--function
.source.coffee .support.class => .syntax--source.syntax--coffee .syntax--support.syntax--class
.source.coffee .comment .storage.type.class => .syntax--source.syntax--coffee .syntax--comment .syntax--storage.syntax--type.syntax--class
.source.crystal .support.class.struct, .source.crystal .keyword.control.unsigned-int, .source.crystal .keyword.control.signed-int, .source.crystal .keyword.control.float => .syntax--source.syntax--crystal .syntax--support.syntax--class.syntax--struct, .syntax--source.syntax--crystal .syntax--keyword.syntax--control.syntax--unsigned-int, .syntax--source.syntax--crystal .syntax--keyword.syntax--control.syntax--signed-int, .syntax--source.syntax--crystal .syntax--keyword.syntax--control.syntax--float
.source.crystal .support.function.kernel, .source.crystal .keyword.other.special-method => .syntax--source.syntax--crystal .syntax--support.syntax--function.syntax--kernel, .syntax--source.syntax--crystal .syntax--keyword.syntax--other.syntax--special-method
.source.css .entity.tag, .source.css .entity.attribute-name => .syntax--source.syntax--css .syntax--entity.syntax--tag, .syntax--source.syntax--css .syntax--entity.syntax--attribute-name
.source.css .entity.tag .entity.attribute-name, .source.css .entity.attribute-name .entity.attribute-name => .syntax--source.syntax--css .syntax--entity.syntax--tag .syntax--entity.syntax--attribute-name, .syntax--source.syntax--css .syntax--entity.syntax--attribute-name .syntax--entity.syntax--attribute-name
.source.css .entity.tag .punctuation.definition, .source.css .entity.attribute-name .punctuation.definition => .syntax--source.syntax--css .syntax--entity.syntax--tag .syntax--punctuation.syntax--definition, .syntax--source.syntax--css .syntax--entity.syntax--attribute-name .syntax--punctuation.syntax--definition
.source.css .support.constant => .syntax--source.syntax--css .syntax--support.syntax--constant
.source.css .constant.rgb-value => .syntax--source.syntax--css .syntax--constant.syntax--rgb-value
.source.css .keyword.important => .syntax--source.syntax--css .syntax--keyword.syntax--important
.source.css .keyword.other.unit => .syntax--source.syntax--css .syntax--keyword.syntax--other.syntax--unit
.source.css .punctuation.terminator, .source.css .punctuation.separator => .syntax--source.syntax--css .syntax--punctuation.syntax--terminator, .syntax--source.syntax--css .syntax--punctuation.syntax--separator
.source.elixir .keyword.other.special-method => .syntax--source.syntax--elixir .syntax--keyword.syntax--other.syntax--special-method
.source.elixir .constant.language => .syntax--source.syntax--elixir .syntax--constant.syntax--language
.source.elixir .constant.symbol .punctuation.definition => .syntax--source.syntax--elixir .syntax--constant.syntax--symbol .syntax--punctuation.syntax--definition
.source.elixir.embedded .keyword.other.special-method, .source.elixir.embedded .constant.language => .syntax--source.syntax--elixir.syntax--embedded .syntax--keyword.syntax--other.syntax--special-method, .syntax--source.syntax--elixir.syntax--embedded .syntax--constant.syntax--language
.source.elm .meta.import .keyword.other => .syntax--source.syntax--elm .syntax--meta.syntax--import .syntax--keyword.syntax--other
.source.elm .support.type, .source.elm .storage.type => .syntax--source.syntax--elm .syntax--support.syntax--type, .syntax--source.syntax--elm .syntax--storage.syntax--type
.source.elm .constant.other => .syntax--source.syntax--elm .syntax--constant.syntax--other
.source.elm .support.constant => .syntax--source.syntax--elm .syntax--support.syntax--constant
.source.gfm .markup.heading => .syntax--source.syntax--gfm .syntax--markup.syntax--heading
.source.gfm .markup.heading .heading => .syntax--source.syntax--gfm .syntax--markup.syntax--heading .syntax--heading
.source.gfm .markup.heading .marker => .syntax--source.syntax--gfm .syntax--markup.syntax--heading .syntax--marker
.source.gfm .markup.code, .source.gfm .markup.raw => .syntax--source.syntax--gfm .syntax--markup.syntax--code, .syntax--source.syntax--gfm .syntax--markup.syntax--raw
.source.gfm .markup.code .support.function.actionpack, .source.gfm .markup.raw .support.function.actionpack, .source.gfm .markup.code .support.function.viewhelpers, .source.gfm .markup.raw .support.function.viewhelpers, .source.gfm .markup.code .support.function.activerecord, .source.gfm .markup.raw .support.function.activerecord, .source.gfm .markup.code .support.function.activesupport, .source.gfm .markup.raw .support.function.activesupport, .source.gfm .markup.code .keyword.special-method, .source.gfm .markup.raw .keyword.special-method, .source.gfm .markup.code .variable.this, .source.gfm .markup.raw .variable.this, .source.gfm .markup.code .keyword.new, .source.gfm .markup.raw .keyword.new, .source.gfm .markup.code .constant.numeric, .source.gfm .markup.raw .constant.numeric, .source.gfm .markup.code .constant.boolean, .source.gfm .markup.raw .constant.boolean, .source.gfm .markup.code .constant.nil, .source.gfm .markup.raw .constant.nil, .source.gfm .markup.code .constant.keyword, .source.gfm .markup.raw .constant.keyword, .source.gfm .markup.code .string.quoted, .source.gfm .markup.raw .string.quoted, .source.gfm .markup.code .storage.control, .source.gfm .markup.raw .storage.control, .source.gfm .markup.code .storage.var, .source.gfm .markup.raw .storage.var, .source.gfm .markup.code .keyword.control, .source.gfm .markup.raw .keyword.control, .source.gfm .markup.code .constant.symbol, .source.gfm .markup.raw .constant.symbol => .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--support.syntax--function.syntax--actionpack, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--support.syntax--function.syntax--actionpack, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--support.syntax--function.syntax--viewhelpers, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--support.syntax--function.syntax--viewhelpers, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--support.syntax--function.syntax--activerecord, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--support.syntax--function.syntax--activerecord, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--support.syntax--function.syntax--activesupport, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--support.syntax--function.syntax--activesupport, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--keyword.syntax--special-method, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--keyword.syntax--special-method, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--variable.syntax--this, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--variable.syntax--this, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--keyword.syntax--new, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--keyword.syntax--new, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--constant.syntax--numeric, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--constant.syntax--numeric, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--constant.syntax--boolean, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--constant.syntax--boolean, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--constant.syntax--nil, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--constant.syntax--nil, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--constant.syntax--keyword, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--constant.syntax--keyword, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--string.syntax--quoted, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--string.syntax--quoted, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--storage.syntax--control, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--storage.syntax--control, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--storage.syntax--var, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--storage.syntax--var, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--keyword.syntax--control, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--keyword.syntax--control, .syntax--source.syntax--gfm .syntax--markup.syntax--code .syntax--constant.syntax--symbol, .syntax--source.syntax--gfm .syntax--markup.syntax--raw .syntax--constant.syntax--symbol
.source.gfm .markup.italic => .syntax--source.syntax--gfm .syntax--markup.syntax--italic
.source.gfm .markup.bold => .syntax--source.syntax--gfm .syntax--markup.syntax--bold
.source.gfm .markup.strike => .syntax--source.syntax--gfm .syntax--markup.syntax--strike
.source.gfm .link => .syntax--source.syntax--gfm .syntax--link
.source.gfm .link .link => .syntax--source.syntax--gfm .syntax--link .syntax--link
.source.gfm .link .punctuation.definition => .syntax--source.syntax--gfm .syntax--link .syntax--punctuation.syntax--definition
.source.js .comment .storage.type.class => .syntax--source.syntax--js .syntax--comment .syntax--storage.syntax--type.syntax--class
.source.js .meta.tag.jsx .entity.tag => .syntax--source.syntax--js .syntax--meta.syntax--tag.syntax--jsx .syntax--entity.syntax--tag
.source.js .meta.tag.jsx .entity.other.attribute-name.jsx => .syntax--source.syntax--js .syntax--meta.syntax--tag.syntax--jsx .syntax--entity.syntax--other.syntax--attribute-name.syntax--jsx
.source.js .meta.tag.jsx .punctuation.definition.tag, .source.js .meta.tag.jsx .keyword.operator.assignment => .syntax--source.syntax--js .syntax--meta.syntax--tag.syntax--jsx .syntax--punctuation.syntax--definition.syntax--tag, .syntax--source.syntax--js .syntax--meta.syntax--tag.syntax--jsx .syntax--keyword.syntax--operator.syntax--assignment
.source.json .meta.structure.dictionary .string.quoted => .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary .syntax--string.syntax--quoted
.source.json .meta.structure.dictionary .string.quoted .punctuation.definition => .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.source.json .meta.structure.dictionary .array .string.quoted => .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary .syntax--array .syntax--string.syntax--quoted
.source.json .meta.structure.dictionary .array .string.quoted .punctuation.definition => .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary .syntax--array .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.source.json .meta.structure.dictionary .punctuation.key-value => .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary .syntax--punctuation.syntax--key-value
.source.json .meta.structure.dictionary > .value.json > .string.quoted.json, .source.json .meta.structure.array > .value.json > .string.quoted.json => .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary > .syntax--value.syntax--json > .syntax--string.syntax--quoted.syntax--json, .syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--array > .syntax--value.syntax--json > .syntax--string.syntax--quoted.syntax--json
.source.json .constant.language => .syntax--source.syntax--json .syntax--constant.syntax--language
.latex .keyword.control, .latex .support.function => .syntax--latex .syntax--keyword.syntax--control, .syntax--latex .syntax--support.syntax--function
.latex .keyword.control .punctuation, .latex .support.function .punctuation => .syntax--latex .syntax--keyword.syntax--control .syntax--punctuation, .syntax--latex .syntax--support.syntax--function .syntax--punctuation
.latex .meta.preamble .support.class => .syntax--latex .syntax--meta.syntax--preamble .syntax--support.syntax--class
.latex .variable.parameter => .syntax--latex .syntax--variable.syntax--parameter
.latex .constant.other => .syntax--latex .syntax--constant.syntax--other
.latex .punctuation.definition, .latex .punctuation.section => .syntax--latex .syntax--punctuation.syntax--definition, .syntax--latex .syntax--punctuation.syntax--section
.latex .string.quoted => .syntax--latex .syntax--string.syntax--quoted
.latex .string.quoted .punctuation => .syntax--latex .syntax--string.syntax--quoted .syntax--punctuation
.source.less .keyword.control.at-rule .punctuation.definition => .syntax--source.syntax--less .syntax--keyword.syntax--control.syntax--at-rule .syntax--punctuation.syntax--definition
.source.less .variable => .syntax--source.syntax--less .syntax--variable
.source.less .variable.other.interpolation => .syntax--source.syntax--less .syntax--variable.syntax--other.syntax--interpolation
.liquid .constant.language => .syntax--liquid .syntax--constant.syntax--language
.liquid .entity.name.tag => .syntax--liquid .syntax--entity.syntax--name.syntax--tag
.liquid .punctuation.tag.liquid .punctuation.embedded, .liquid .punctuation.output.liquid .punctuation.embedded => .syntax--liquid .syntax--punctuation.syntax--tag.syntax--liquid .syntax--punctuation.syntax--embedded, .syntax--liquid .syntax--punctuation.syntax--output.syntax--liquid .syntax--punctuation.syntax--embedded
.php .storage.type.class, .php .storage.type.function => .syntax--php .syntax--storage.syntax--type.syntax--class, .syntax--php .syntax--storage.syntax--type.syntax--function
.php .constant.language => .syntax--php .syntax--constant.syntax--language
.php .variable.global => .syntax--php .syntax--variable.syntax--global
.php .variable.global .punctuation.definition => .syntax--php .syntax--variable.syntax--global .syntax--punctuation.syntax--definition
.php .variable .punctuation.definition => .syntax--php .syntax--variable .syntax--punctuation.syntax--definition
.php .support.function.construct => .syntax--php .syntax--support.syntax--function.syntax--construct
.php .punctuation.terminator => .syntax--php .syntax--punctuation.syntax--terminator
.php .meta.embedded => .syntax--php .syntax--meta.syntax--embedded
.php .meta.embedded .punctuation.embedded => .syntax--php .syntax--meta.syntax--embedded .syntax--punctuation.syntax--embedded
.source.python .storage.type.class, .source.python .storage.type.function => .syntax--source.syntax--python .syntax--storage.syntax--type.syntax--class, .syntax--source.syntax--python .syntax--storage.syntax--type.syntax--function
.source.python .meta.structure.dictionary.key .numeric, .source.python .meta.structure.dictionary.key .string.quoted => .syntax--source.syntax--python .syntax--meta.syntax--structure.syntax--dictionary.syntax--key .syntax--numeric, .syntax--source.syntax--python .syntax--meta.syntax--structure.syntax--dictionary.syntax--key .syntax--string.syntax--quoted
.source.python .meta.structure.dictionary.key .numeric .punctuation.definition, .source.python .meta.structure.dictionary.key .string.quoted .punctuation.definition => .syntax--source.syntax--python .syntax--meta.syntax--structure.syntax--dictionary.syntax--key .syntax--numeric .syntax--punctuation.syntax--definition, .syntax--source.syntax--python .syntax--meta.syntax--structure.syntax--dictionary.syntax--key .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.source.python .constant.language => .syntax--source.syntax--python .syntax--constant.syntax--language
.source.python .variable.self => .syntax--source.syntax--python .syntax--variable.syntax--self
.ruby .constant.symbol .punctuation.definition => .syntax--ruby .syntax--constant.syntax--symbol .syntax--punctuation.syntax--definition
.ruby .support.function.actionpack, .ruby .support.function.viewhelpers, .ruby .support.function.activerecord, .ruby .support.function.activesupport, .ruby .keyword.special-method => .syntax--ruby .syntax--support.syntax--function.syntax--actionpack, .syntax--ruby .syntax--support.syntax--function.syntax--viewhelpers, .syntax--ruby .syntax--support.syntax--function.syntax--activerecord, .syntax--ruby .syntax--support.syntax--function.syntax--activesupport, .syntax--ruby .syntax--keyword.syntax--special-method
.ruby .meta.embedded .punctuation.embedded, .ruby .source.embedded .punctuation.embedded => .syntax--ruby .syntax--meta.syntax--embedded .syntax--punctuation.syntax--embedded, .syntax--ruby .syntax--source.syntax--embedded .syntax--punctuation.syntax--embedded
.ruby .meta.embedded .support.function.actionpack, .ruby .source.embedded .support.function.actionpack, .ruby .meta.embedded .support.function.viewhelpers, .ruby .source.embedded .support.function.viewhelpers, .ruby .meta.embedded .support.function.activerecord, .ruby .source.embedded .support.function.activerecord, .ruby .meta.embedded .support.function.activesupport, .ruby .source.embedded .support.function.activesupport, .ruby .meta.embedded .keyword.special-method, .ruby .source.embedded .keyword.special-method => .syntax--ruby .syntax--meta.syntax--embedded .syntax--support.syntax--function.syntax--actionpack, .syntax--ruby .syntax--source.syntax--embedded .syntax--support.syntax--function.syntax--actionpack, .syntax--ruby .syntax--meta.syntax--embedded .syntax--support.syntax--function.syntax--viewhelpers, .syntax--ruby .syntax--source.syntax--embedded .syntax--support.syntax--function.syntax--viewhelpers, .syntax--ruby .syntax--meta.syntax--embedded .syntax--support.syntax--function.syntax--activerecord, .syntax--ruby .syntax--source.syntax--embedded .syntax--support.syntax--function.syntax--activerecord, .syntax--ruby .syntax--meta.syntax--embedded .syntax--support.syntax--function.syntax--activesupport, .syntax--ruby .syntax--source.syntax--embedded .syntax--support.syntax--function.syntax--activesupport, .syntax--ruby .syntax--meta.syntax--embedded .syntax--keyword.syntax--special-method, .syntax--ruby .syntax--source.syntax--embedded .syntax--keyword.syntax--special-method
.ruby .meta.embedded .string.quoted .punctuation.definition, .ruby .source.embedded .string.quoted .punctuation.definition => .syntax--ruby .syntax--meta.syntax--embedded .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition, .syntax--ruby .syntax--source.syntax--embedded .syntax--string.syntax--quoted .syntax--punctuation.syntax--definition
.source.rust .keyword.other => .syntax--source.syntax--rust .syntax--keyword.syntax--other
.source.rust .storage.type => .syntax--source.syntax--rust .syntax--storage.syntax--type
.source.rust .comment .storage => .syntax--source.syntax--rust .syntax--comment .syntax--storage
.source.sass .meta.selector .class => .syntax--source.syntax--sass .syntax--meta.syntax--selector .syntax--class
.source.sass .meta.selector .class .punctuation.definition => .syntax--source.syntax--sass .syntax--meta.syntax--selector .syntax--class .syntax--punctuation.syntax--definition
.source.sass .entity.tag => .syntax--source.syntax--sass .syntax--entity.syntax--tag
.source.sass .meta .variable.other => .syntax--source.syntax--sass .syntax--meta .syntax--variable.syntax--other
.source.sass .support.constant => .syntax--source.syntax--sass .syntax--support.syntax--constant
.source.scss .meta .variable => .syntax--source.syntax--scss .syntax--meta .syntax--variable
.source.scss .punctuation.separator.key-value, .source.scss .punctuation.terminator => .syntax--source.syntax--scss .syntax--punctuation.syntax--separator.syntax--key-value, .syntax--source.syntax--scss .syntax--punctuation.syntax--terminator
.source.shell .support.function.builtin => .syntax--source.syntax--shell .syntax--support.syntax--function.syntax--builtin
.source.shell .string.quoted .variable .punctuation => .syntax--source.syntax--shell .syntax--string.syntax--quoted .syntax--variable .syntax--punctuation
.slim .entity.name.tag, .slim .punctuation.definition.tag => .syntax--slim .syntax--entity.syntax--name.syntax--tag, .syntax--slim .syntax--punctuation.syntax--definition.syntax--tag
.slim .entity.attribute-name => .syntax--slim .syntax--entity.syntax--attribute-name
.yaml .constant.numeric => .syntax--yaml .syntax--constant.syntax--numeric
.yaml .entity.tag => .syntax--yaml .syntax--entity.syntax--tag
.yaml .entity.tag .punctuation => .syntax--yaml .syntax--entity.syntax--tag .syntax--punctuation
.settings-embedded-mix .punctuation.embedded => .settings-embedded-mix .syntax--punctuation.syntax--embedded

**Comment by biletskyy** [comment]
fixed. sorry for long delay.
