### ISSUE TITLE
Add support for Golang

### ISSUE THREAD

**Issue by albertorestifo** [biletskyy/flatwhite-syntax#6]
Would be fantastic to have support for Golang

**Comment by biletskyy** [comment]
Thanks for your interest to this theme. I added basic support for Golang. But I had zero experience with Golang, so it might be suboptimal or incomplete. I will look into it in more depth in the future. And I will appreciate your comments and suggestion.

**Comment by albertorestifo** [comment]
Sure, I'll check out the change a let you know if I've specific feedback or maybe make a PR myself.

Keep up the good work!

**Comment by albertorestifo** [comment]
Just one small things, maybe hilight the types?

![](https://i.imgur.com/oQKDHyx.png)

In this example the `string` keyword has the following classes: `storage type string go`

**Comment by biletskyy** [comment]
Yes, I agree with your suggestion. Updated the theme.
