### ISSUE TITLE
Don't !important font-style

### ISSUE THREAD

**Issue by lucasmotta** [biletskyy/flatwhite-syntax#8]
https://github.com/biletskyy/flatwhite-syntax/blob/eabc010cd972a5c871109e740f2edc9d7db4ef64/styles/languages/javascript.less#L29

I love this theme, but I want my attributes to be italic (especially on JSX) - is there any reason you are setting this to important?

Thanks!

**Comment by biletskyy** [comment]
Thank you for your interest to this theme. 
I made this attributes secondary text color and babel package made them italic. And that way they became similar to comment style.

So I decided to make them in sync with html attributes. But now i see that they are not in sync with every other babel powered theme, which is bad.

So I'll try to redo it one more time and find the solution to this issue.

**Comment by biletskyy** [comment]
I changed attributes everywhere to italic. Also added different secondary color for them.
