### ISSUE TITLE
Is there an shortcut ?

### ISSUE THREAD

**Issue by sarpaykent** [biletskyy/flatwhite-syntax#9]
Hey, I just installed the package but nothing changed. I need to select the text or need to use shortcut ?

**Comment by biletskyy** [comment]
Sorry, but i don't understood your question. 
This is a syntax theme. You install it, then go to "Themes" and in the dropdown "Syntax Theme" you select it. If that's what you asking about.

**Comment by sarpaykent** [comment]
Oh, okay sorry for that. I miss understood. I suppose its for highlighting different languages
